#开发配置

#web
server:
  port: 8888
#resources datasource freemarker
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:thin:47.106.185.221:3306:gamerdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: gamer
    password: gamer123456
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    request-context-attribute: request
    charset: utf-8
    enabled: true
    cache: false
    check-template-location: true
    content-type: text/html
    expose-session-attributes: true
    expose-request-attributes: true

#mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*/*Mapper.xml
  type-aliases-package: com.ral.manages.entity

#log
#logging:
#  config: classpath:logback.xml
#  path: E://log
